<h2>Privacy Policy</h2>
<p>Your privacy is important to us. At OBFX, we treat all information collected by, or transmitted to us with care, in particular, personally identifiable information, and this Policy describes how, when, and why we collect such information. Personally identifiable information (“Personal Information”) means any information that may be used, either alone or in combination with other information, to personally identify, contact or locate an individual. This may include, but is not limited to, forename, first name, ID, Passport number, address, e-mail, credit/debit card details, financial data (including trading data, deposits, withdrawals, and credit) and other contact information. Any information that does not enable identification, location, or contacting of an individual, such as aggregated information, is “Anonymous Information”, and OBFX. may process Anonymous Information in any way it so considers without prior notice to you.</p>
<h5>CONSENT, NOTIFICATION AND MODIFICATION</h5>
<p>Upon using the Website, you authorize us to collect the Personal Information and to the extent necessary to manage your account and to improve services and information we send you. This information can be sent to any entity that contributes to the service provided to you such as those responsible for the execution of services and orders for their management, execution, processing and payment.</p>
<p>In addition, as a recipient of our service, you commit to provide appropriate notice of your privacy practices to, and obtain the necessary permissions and consent from, any third parties with whom you engage and/or whose Personal Information is collected, received, used, and/or disclosed by us.</p>
<p>The Personal Information is stored for security purposes, to meet legal and regulatory obligations. You have a right of access, rectification and opposition to your Personal Information. This also includes a right to unsubscribe from emails that will be sent to you from time to time.</p>
<p>We reserve the right, in our discretion and subject to the applicable law, to amend this Privacy Policy at any time and. Any amendment shall be effective within 15 days following the posting of the changed Policy on our Website, and your continued Use of the service shall constitute consent to the terms and provisions of the amended Policy.</p>
<h5>COLLECTION AND RECEIPT OF INFORMATION</h5>
<p>We collect and receive Personal Information pertaining to traders. This occurs due to the fact that, as part of the service, we may provide hosting services for some or all of the services, resulting in trader-related Personal Information being routed to us from our production servers. We also collect and receive Personal Information relating to certain employees of our clients for the purposes of communication with us and the general provision of the Service.</p>
<p>The service may also use “cookies” and other tracking technologies to collect Anonymous Information. A “cookie” is a small text file that may be used, for example, to collect information about service activity and it may serve to recall Personal Information previously indicated by a trader, such as his/her user ID and password for access to the service(s).</p>
<h5>USE AND DISCLOSURE OF PERSONAL INFORMATION</h5>
<p>We will store your Personal Information in our system and use it for the following purposes only:</p>
<ul>
<li>Managing the administrative aspects of the services, providing you with support, handling complaints and contacting you;</li>
<li>Handling your orders;</li>
<li>Enforcing this Policy and the Terms and Conditions, preventing misuse of the Website, complying with legal requirements, assisting competent authorities, and taking action in case of a dispute involving you, with respect to the service we provide;</li>
<li>Improving the Website and the services, develop new services and improve the accuracy and reliability of the services.</li>
</ul>
<h5>NON-AFFILIATED THIRD PARTIES AND THE TRANSFER OF INFORMATION OUTSIDE YOUR TERRITORY</h5>
<p>We do not sell, license, lease or otherwise disclose Personal Information to any third party for any reason, except as described below. We reserves the right to disclose your personal information to third parties where required by law to regulatory, law enforcement or other government authorities. We may also disclose your information as necessary to credit reporting or collection agencies, or when necessary to protect our rights or property.</p>
<p>To help us improve our services to you, we may engage another business to help us to carry out certain internal functions such as account processing, fulfillment, client service, deliver and safe keeping as indicated in the Terms and Conditions.</p>
<p>Use of the information shared is strictly limited to the performance of the task we request and for no other purpose. All third parties with whom we share personal information is required to protect personal information in a manner similar to the way we protect personal information. Examples of information shared are identifying information such as name, mailing address, e-mail address, telephone number and information on account activity.</p>
<p>If at any time you choose to purchase a product or service offered by another company/individual, any personal information you share with it will no longer be controlled under our Privacy Policy. We are not responsible for the privacy policies or the content of sites we link to and we have no control of the use or protection of information provided by you or collected by those sites. Whenever you elect to link to a co-branded web site or to a linked Web site, you may be asked to provide registration or other information. Please note that the information you are providing is going to a third party, and you should familiarize yourself with the privacy policy published by that third party.</p>
<h5>SECURITY</h5>
<p>We take reasonable precautions to protect Personal Information from loss, theft, misuse, unauthorized access or disclosure, alteration, or destruction. This is done by using physical, electronic, and procedural safeguards to protect Personal Information and we do not store Personal Information for longer than necessary to provide the service or as permitted by law. Though we implement measures to reduce the risks of damage, loss and unauthorized access to Personal Information, they do not provide absolute information security. Therefore, it is not guaranteed, and you cannot reasonably expect, that the service will be immune from any unauthorized interceptions or access.</p>